[module]
  [module.hugoVersion]
    min = "0.115.4"
[params]
email="amanda.norton74@gmail.com"
dateform="2006-01-02"
linkedin = "https://linkedin.com/in/amanda-norton-mph-7aaaa51b8/"
github = "https://github.com/mandarnorton"
twitter = "https://x.com/amandanortongeo"