[module]
  [module.hugoVersion]
    min = "0.115.4"
[params]
email="amanda.norton74@gmail.com"
dateform="2006-01-02"
linkedin = "https://linkedin.com/me/amanda-norton"
github = "https://github.com/mandarnorton"
twitter = "https://x.com/amandanortongeo"